version: '2'
services:

  mongodb:
    image: mongo:latest
    volumes:
      - $HOME/projects/mongodb:/data/db
    ports:
      - 27017:27017

  semanitcs3:
      build:  .
      ports: 
        # - 27017:27017
        - 3000:3000
      depends_on: 
        - mongodb
    
networks:
  esnet1:
    driver: bridge
