var fetch = require("node-fetch");
var port = process.env.PORT || 3000;

var handles = [
  "Katyperry",
  "justinbieber",
  "taylorswift13",
  "BarackObama",
  "rihanna",
  "YouTube",
  "ladygaga",
  "TheEllenShow",
  "twitter",
  "jtimberlake",
  "KimKardashian",
  "britneyspears",
  "Cristiano",
  "selenagomez",
  "jimmyfallon",
  "ArianaGrande",
  "cnnbrk",
  "instagram",
  "shakira",
  "ddlovato",
  "JLo",
  "Drake",
  "Oprah",
  "KingJames",
  "BillGates",
  "KevinHart4real",
  "MileyCyrus",
  "onedirection",
  "Nytimes",
  "Harry_Styles",
  "SportsCenter",
  "espn",
  "Pink",
  "wizkhalifa",
  "NiallOfficial",
  "Adele",
  "LilTunechi",
  "BrunoMars",
  "kanyewest",
  "ActuallyNPH",
  "neymarjr",
  "KAKA",
  "narendramodi",
  "LiamPayne",
  "NBA",
  "Louis_Tomlinson",
  "Aliciakeys",
  "SrBachchan",
  "CNN",
  "EmWatson",
  "BBCBreaking",
  "danieltosh",
  "pitbull",
  "Iamsrk",
  "ConanOBrien",
  "NICKIMINAJ",
  "NFL",
  "zaynmalik",
  "davidguetta",
  "AvrilLavigne",
  "Eminem",
  "BeingSalmanKhan",
  "NASA",
  "KylieJenner",
  "blakeshelton",
  "aamir_khan",
  "khloekardashian",
  "realmadrid",
  "coldplay",
  "FCBarcelona",
  "kourtneykardash",
  "aplusk",
  "vine",
  "edsheeran",
  "KendallJenner",
  "deepikapadukone",
  "google",
  "xtina",
  "MohamadAlarefe",
  "agnezmo",
  "MariahCarey",
  "shugairi",
  "LeoDiCaprio",
  "TwitterEspanol",
  "chrisbrown",
  "JimCarrey",
  "ricky_martin",
  "KDTrey5",
  "ivetesangalo",
  "BBCWorld",
  "iHrithik",
  "priyankachopra",
  "TheEconomist",
  "Reuters",
  "TwitterSports",
  "SnoopDogg",
  "Beyonce",
  "RyanSeacrest",
  "AlejandroSanz",
  "radityadika"
];

let index = 0;

function callAPI() {
  const handle = handles[index];
  let url = "http://localhost:" + port + "/api/users/add";
  fetch(url, {
    method: "POST",
    body: JSON.stringify({ handle: handle }),
    headers: { "Content-Type": "application/json" }
  })
    .then(response => response.text())
    .then(html => {
      console.log(html);
      ++index;
    });
}

setInterval(callAPI, 5 * 60 * 1000);
